credentials:
  # You can obtain monitoring data of multiple tenants by configuring multiple Tenant information.
  tenant1:
    accessKey: xxxxxxxxxxxx
    accessKeySecret: xxxxxxxxxxxx
    region_id: hangzhou
  tenant2:
    accessKey: xxxxxxxxxxxx
    accessKeySecret: xxxxxxxxxxxx
    region_id: hangzhou
# ......

metrics:
  acs_ecs_dashboard:
    - name: CPUUtilization
      desc: CPU使用率
      dimensions:
        - userId
        - instanceId
      measure: Average
      period: 1200
      unit: "%"
    - name: InternetInRate
      desc: 公网流入流量平均速率
      dimensions:
        - userId
        - instanceId
      measure: Average
      period: 1200
      unit: "bit/s"
    - name: InternetOutRate
      desc: 公网流出流量平均速率
      dimensions:
        - userId
        - instanceId
      measure: Average
      period: 1200
      unit: "bit/s"
    - name: IntranetInRate
      desc: 内网流入流量平均速率
      dimensions:
        - userId
        - instanceId
      measure: Average
      period: 1200
      unit: "bit/s"
    - name: IntranetOutRate
      desc: 内网流出带宽使用率
      dimensions:
        - userId
        - instanceId
      measure: Average
      period: 1200
      unit: "bit/s"
    - name: DiskReadBPS
      desc: 所有磁盘读取BPS
      dimensions:
        - userId
        - instanceId
      measure: Average
      period: 1200
      unit: "Byte/s"
    - name: DiskWriteBPS
      desc: 所有磁盘写入BPS
      dimensions:
        - userId
        - instanceId
      measure: Average
      period: 1200
      unit: "Byte/s"
    - name: DiskReadIOPS
      desc: 所有磁盘每秒读取次数
      dimensions:
        - userId
        - instanceId
      measure: Average
      period: 1200
      unit: "Count/Second"
    - name: DiskWriteIOPS
      desc: 所有磁盘每秒写入次数
      dimensions:
        - userId
        - instanceId
      measure: Average
      period: 1200
      unit: "Count/Second"
    - name: InternetIn
      desc: 公网流入流量
      dimensions:
        - userId
        - instanceId
      measure: Average
      period: 1200
      unit: "Byte"
    - name: InternetOut
      desc: 公网流出流量
      dimensions:
        - userId
        - instanceId
      measure: Average
      period: 1200
      unit: "Byte"
    - name: IntranetIn
      desc: 内网流入流量
      dimensions:
        - userId
        - instanceId
      measure: Average
      period: 1200
      unit: "Byte"
    - name: IntranetOut
      desc: 内网流出流量
      dimensions:
        - userId
        - instanceId
      measure: Average
      period: 1200
      unit: "Byte"
