{
 "title": "Aliyun ECS Dashboard",
 "description": "Alibaba Cloud ECS Instance Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cloudID",
    "query": {
     "query": "label_values(cloudmonitor_acs_ecs_dashboard_CPUUtilization, cloudID)"
    }
   },
   {
    "name": "instanceId",
    "query": {
     "query": "label_values(cloudmonitor_acs_ecs_dashboard_CPUUtilization, instanceId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization Percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cloudmonitor_acs_ecs_dashboard_CPUUtilization{instanceId=\"$instanceId\"}",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "Concurrent Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cloudmonitor_acs_ecs_dashboard_concurrentConnections{instanceId=\"$instanceId\"}",
     "legendFormat": "Concurrent Connections (Counts)"
    }
   ]
  },
  {
   "title": "Intranet Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(cloudmonitor_acs_ecs_dashboard_IntranetIn{instanceId=\"$instanceId\"})",
     "legendFormat": "Rx"
    },
    {
     "expr": "sum(cloudmonitor_acs_ecs_dashboard_IntranetOut{instanceId=\"$instanceId\"})",
     "legendFormat": "Tx"
    }
   ]
  },
  {
   "title": "Internet Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(cloudmonitor_acs_ecs_dashboard_InternetIn{instanceId=\"$instanceId\"})",
     "legendFormat": "Rx"
    },
    {
     "expr": "sum(cloudmonitor_acs_ecs_dashboard_InternetOut{instanceId=\"$instanceId\"})",
     "legendFormat": "Tx"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "cloudmonitor_acs_ecs_dashboard_DiskReadBPS{instanceId=\"$instanceId\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "cloudmonitor_acs_ecs_dashboard_DiskWriteBPS{instanceId=\"$instanceId\"}",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "cloudmonitor_acs_ecs_dashboard_DiskReadIOPS{instanceId=\"$instanceId\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "cloudmonitor_acs_ecs_dashboard_DiskWriteIOPS{instanceId=\"$instanceId\"}",
     "legendFormat": "Write"
    }
   ]
  }
 ]
}